import json

lineas_metro = {
  "metro": {
    "linea_1":[
      "Pinar de Chamartín",
      "Bambú",
      "Chamartín",
      "Plaza de Castilla",
      "Valdeacederas",
      "Tetuán",
      "Estrecho",
      "Alvarado",
      "Cuatro Caminos",
      "Ríos Rosas",
      "Iglesia",
      "Bilbao",
      "Tribunal",
      "Gran Vía",
      "Sol",
      "Tirso de Molina",
      "Antón Martín",
      "Estación del Arte",
      "Atocha",
      "Menéndez Pelayo",
      "Pacífico",
      "Puente de Vallecas",
      "Nueva Numancia",
      "Portazgo",
      "Buenos Aires",
      "Alto del Arenal",
      "Miguel Hernández",
      "Sierra de Guadalupe",
      "Villa de Vallecas",
      "Congosto",
      "La Gavia",
      "Las Suertes",
      "Valdecarros"
    ],
    "linea_2":[
      "Las Rosas",
      "Avenida de Guadalajara",
      "Alsacia",
      "La Almudena",
      "La Elipa",
      "Ventas",
      "Manuel Becerra",
      "Goya",
      "Príncipe de Vergara",
      "Retiro",
      "Banco de España",
      "Sevilla",
      "Sol",
      "Ópera",
      "Santo Domingo",
      "Noviciado",
      "San Bernardo",
      "Quevedo",
      "Canal",
      "Cuatro Caminos"
    ],
    "linea_3":[
      "El Casar",
      "Villaverde Alto",
      "San Cristóbal",
      "Villaverde Bajo-Cruce",
      "Ciudad de los Ángeles",
      "San Fermín-Orcasur",
      "Hospital 12 de Octubre",
      "Almendrales",
      "Legazpi",
      "Delicias",
      "Palos de la Frontera",
      "Embajadores",
      "Lavapiés",
      "Sol",
      "Callao",
      "Plaza de España",
      "Ventura Rodríguez",
      "Argüelles",
      "Moncloa"
    ],
    "linea_4": [
      "Argüelles",
      "San Bernardo",
      "Bilbao",
      "Alonso Martínez",
      "Colón",
      "Serrano",
      "Velázquez",
      "Goya",
      "Lista",
      "Diego de León",
      "Avenida de América",
      "Prosperidad",
      "Alfonso XIII",
      "Avenida de la Paz",
      "Arturo Soria",
      "Esperanza",
      "Canillas",
      "Mar de Cristal",
      "San Lorenzo",
      "Parque de Santa María",
      "Hortaleza",
      "Manoteras",
      "Pinar de Chamartín"
    ],
    "linea_5":[
      "Alameda de Osuna",
      "El Capricho",
      "Canillejas",
      "Torre Arias",
      "Suanzes",
      "Ciudad lineal",
      "Pueblo Nuevo",
      "Quintana",
      "El Carmen",
      "Ventas",
      "Diego de León",
      "Núñez de Balboa",
      "Rubén Darío",
      "Alonso Martínez",
      "Chueca",
      "Gran Vía",
      "Callao",
      "Ópera",
      "La Latina",
      "Puerta de Toledo",
      "Acacias",
      "Pirámides",
      "Marqués de Vadillo",
      "Urgel",
      "Oporto",
      "Vista Alegre",
      "Carabanchel",
      "Eugenia de Montijo",
      "Aluche",
      "Empalme",
      "Campamento",
      "Casa de Campo"
    ],
    "linea_6":[
      "Laguna",
      "Carpetana",
      "Oporto",
      "Opañel",
      "Plaza Elíptica",
      "Usera",
      "Legazpi",
      "Arganzuela-Planetario",
      "Méndez Álvaro",
      "Pacífico",
      "Conde de Casal",
      "Sainz de Baranda",
      "O'Donnell",
      "Manuel Becerra",
      "Diego de León",
      "Avenida de América",
      "República Argentina",
      "Nuevos Ministerios",
      "Cuatro Caminos",
      "Guzmán el Bueno",
      "Vicente Aleixandre",
      "Ciudad Universitaria",
      "Moncloa",
      "Argüelles",
      "Príncipe Pío",
      "Puerta del Ángel",
      "Alto de Extremadura",
      "Lucero"
    ],
    "linea_7":[
      "Pitis",
      "Arroyofresno",
      "Lacoma",
      "Avenida de la Ilustración",
      "Peñagrande",
      "Antonio Machado",
      "Valdezarza",
      "Francos Rodríguez",
      "Guzmán el Bueno",
      "Islas Filipinas",
      "Canal",
      "Alonso Cano",
      "Gregorio Marañón",
      "Avenida de América",
      "Cartagena",
      "Parque de las Avenidas",
      "Barrio de la Concepción",
      "Pueblo Nuevo",
      "Ascao",
      "García Noblejas",
      "Simancas",
      "San Blas",
      "Las Musas",
      "Estadio Metropolitano",
      "Barrio del Puerto",
      "Coslada Central",
      "La Rambla",
      "San Fernando",
      "Jarama",
      "Henares",
      "Hospital del Henares"
    ],
    "linea_8":[
      "Nuevos Ministerios",
      "Colombia",
      "Pinar del Rey",
      "Mar de Cristal",
      "Feria de Madrid",
      "Aeropuerto T1-T2-T3",
      "Barajas",
      "Aeropuerto T4"
    ],
    "linea_9":[
      "Paco de Lucía",
      "Mirasierra",
      "Herrera Oria",
      "Barrio del Pilar",
      "Ventilla",
      "Plaza de Castilla",
      "Duque de Pastrana",
      "Pío XII",
      "Colombia",
      "Concha Espina",
      "Cruz del Rayo",
      "Avenida de América",
      "Núñez de Balboa",
      "Príncipe de Vergara",
      "Ibiza",
      "Sainz de Baranda",
      "Estrella",
      "Vinateros",
      "Artilleros",
      "Pavones",
      "Valdebernardo",
      "Vicálvaro",
      "San Cipriano",
      "Puerta de Arganda",
      "Rivas Urbanizaciones",
      "Rivas Futura",
      "Rivas Vaciamadrid",
      "La Poveda",
      "Arganda del Rey"
    ],
    "linea_10":[
      "Hospital Infanta Sofía",
      "Reyes Católicos",
      "Baunatal",
      "Manuel de Falla",
      "Marqués de la Valdavia",
      "La Moraleja",
      "La Granja",
      "Ronda de la Comunicación",
      "Las Tablas",
      "Montecarmelo",
      "Tres Olivos",
      "Fuencarral",
      "Begoña",
      "Chamartín",
      "Plaza de Castilla",
      "Cuzco",
      "Santiago Bernabéu",
      "Nuevos Ministerios",
      "Gregorio Marañón",
      "Alonso Martínez",
      "Tribunal",
      "Plaza de España",
      "Príncipe Pío",
      "Lago",
      "Batán",
      "Casa de Campo",
      "Colonia Jardín",
      "Aviación Española",
      "Cuatro Vientos",
      "Joaquín Vilumbrales",
      "Puerta del Sur"
    ],
    "linea_11":[
      "Plaza Elíptica",
      "Abrantes",
      "Pan Bendito",
      "San Francisco",
      "Carabanchel Alto",
      "La Peseta",
      "La Fortuna"
    ],
    "linea_12":[
      "Puerta del Sur",
      "Parque Lisboa",
      "Alcorcón Central",
      "Parque Oeste",
      "Universidad Rey Juan Carlos",
      "Móstoles Central",
      "Pradillo",
      "Hospital de Móstoles",
      "Manuela Malasaña",
      "Loranca",
      "Hospital de Fuenlabrada",
      "Parque Europa",
      "Fuenlabrada Central",
      "Parque de los Estados",
      "Arroyo Culebro",
      "Conservatorio",
      "Alonso de Mendoza",
      "Getafe Central",
      "Juan de la Cierva",
      "El Casar",
      "Los Espartales",
      "El Bercial",
      "El Carrascal",
      "Julián Besteiro",
      "Casa del Reloj",
      "Hospital Severo Ochoa",
      "Leganés Central",
      "San Nicasio"
    ]
  },
  "metros_ligeros": {
    "metro_ligero_(ML1)": [
      "Pinar de Chamartín",
      "Fuente de la Mora",
      "Virgen del Cortijo",
      "Antonio Saura",
      "Álvarez de Villaamil",
      "Blasco Ibáñez",
      "María Tudor",
      "Palas de Rey",
      "Las Tablas"
    ],
    "metro_ligero_(ML2)": [
      "Colonia Jardín",
      "Prado de la Vega",
      "Colonia de los Ángeles",
      "Prado del Rey",
      "Somosaguas Sur",
      "Somosaguas Centro",
      "Pozuelo Oeste",
      "Bélgica",
      "Dos Castillas",
      "Campus de Somosaguas",
      "Avenida de Europa",
      "Berna",
      "Estación de Aravaca"
    ],
    "metro_ligero_(ML3)": [
      "Colonia Jardín",
      "Ciudad de la Imagen",
      "José Isbert",
      "Ciudad del Cine",
      "Cocheras",
      "Retamares",
      "Retamares Oeste",
      "Montepríncipe",
      "Ventorro del Cano",
      "Prado del Espino",
      "Ciudad Financiera Este",
      "Cantabria",
      "Ciudad Financiera Oeste",
      "Ferial de Boadilla",
      "Boadilla Centro",
      "Nuevo Mundo",
      "Siglo XXI",
      "Infante Don Luis",
      "Puerta de Boadilla"
    ]
  },
  "ramales": {
    "ramal": [
      "Ópera",
      "Príncipe Pío"
    ]
  }
}

# Guardar el diccionario en un archivo JSON
with open("lineas_metro.json", "w", encoding="utf-8") as f:
    json.dump(lineas_metro, f, ensure_ascii=False, indent=4)

print("Diccionario guardado en 'datos.json'")